version: '3.8'
services:
  # Guacamole Daemon
  guacd:
    image: guacamole/guacd:1.5.4
    container_name: guacd
    restart: unless-stopped
    networks:
      - guacamole-net

  # PostgreSQL Database for Guacamole
  postgres:
    image: postgres:15-alpine
    container_name: guacamole-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: guacamole_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d:ro
    networks:
      - guacamole-net

  # Guacamole Web Application
  guacamole:
    image: guacamole/guacamole:1.5.4
    container_name: guacamole
    restart: unless-stopped
    environment:
      GUACD_HOSTNAME: guacd
      GUACD_PORT: 4822
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: guacamole_password
    ports:
      - "8080:8080"
    depends_on:
      - guacd
      - postgres
    networks:
      - guacamole-net

networks:
  guacamole-net:
    driver: bridge

volumes:
  postgres_data: